website/auth.py
import os
from flask import Blueprint, render_template, request, flash, redirect, url_for, session
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
import stripe
from .models import User,Product,CartItem,Cart
from . import db
from .forms import ProductForm
from flask_mail import Message
from . import mail
from werkzeug.utils import secure_filename



auth = Blueprint('auth', __name__)

@auth.route('/login.html', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template('login.html', user=current_user)


@auth.route('/logout')
@login_required
def logout():
    session.clear()
    logout_user()
    flash('Logged out successfully!', category='success')
    return redirect(url_for('auth.login'))


@auth.route('/sign_up.html', methods=['GET', 'POST'])
def create_user():
    if request.method == 'POST':
        new_user = User(email=request.form['email'], first_name=request.form['firstName'], password=generate_password_hash(request.form['password1'],  method='pbkdf2:sha256'))
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user, remember=True)
        send_registration_email(new_user.email, new_user.first_name)

        flash('Account created!', category='success')
        return redirect(url_for('views.created'))
    return render_template('sign_up.html', user=current_user)


@auth.route('/send_email')
def send_registration_email(email, first_name):
    msg = Message(
        'Welcome to Our eShop!',
        recipients=[email])
    
    msg.body = f'Hi {first_name},\n\nThank you for registering at our eShop!'
    
    # # Optional: You can use an HTML template for better-looking emails
    # msg.html = render_template('email_welcome.html', username=username)



    try:
        mail.send(msg)
        print(f"Email sent to {email}")
    except Exception as e:
        print(f"Failed to send email: {e}")


@auth.route('/addproduct.html', methods=['GET', 'POST'])
def add_product():
    form = ProductForm()
    if form.validate_on_submit():
        name = form.name.data
        price = form.price.data
        description = form.description.data
        photo = form.photo.data
        
        
        if photo:
            filename = secure_filename(photo.filename)
            photo_path = os.path.join('/home/jacobsalib/eshop/website/static/images',  filename)
            photo.save(photo_path)

        product = Product(name=name, price=price, description=description, photo=photo_path)
        db.session.add(product)
        db.session.commit()
        return redirect(url_for('auth.add_product'))

    products = Product.query.all()
    return render_template('addproduct.html', products=products, form=form)


@auth.route('/add_to_cart/<int:product_id>', methods=['POST'])
@login_required
def add_to_cart(product_id):
    product = Product.query.get_or_404(product_id)
    
    user_cart = Cart.query.filter_by(user_id=current_user.id).first()

    if not user_cart:
        user_cart = Cart(user_id=current_user.id)
        db.session.add(user_cart)
        db.session.commit()

    # Check if the item is already in the cart
    cart_item = CartItem.query.filter_by(cart_id=user_cart.id, product_id=product.id).first()

    if cart_item:
        cart_item.quantity += 1  
    else:
        new_cart_item = CartItem(cart_id=user_cart.id, product_id=product.id, quantity=1)
        db.session.add(new_cart_item)

    db.session.commit()

    flash('Item added to cart', 'success')
    return redirect(url_for('auth.view_cart'))


@auth.route('/remove_from_cart/<int:item_id>', methods=['POST'])
@login_required
def remove_from_cart(item_id):
    cart_item = CartItem.query.filter_by(id=item_id, cart_id=current_user.id).first()

    if cart_item:
        db.session.delete(cart_item)
        db.session.commit()
        flash('Item removed from cart.', 'success')
    else:
        flash('Item not found or does not belong to your cart.', 'danger')

    return redirect(url_for('auth.view_cart'))


@auth.route('/increase_quantity/<int:item_id>', methods=['POST'])
@login_required
def increase_quantity(item_id):
    cart_item = CartItem.query.filter_by(id=item_id, cart_id=current_user.id).first()

    if cart_item:
        cart_item.quantity += 1  
        db.session.commit()
        flash(f'Added one more {cart_item.product.name} to your cart.', 'success')
    else:
        flash('Item not found in your cart.', 'danger')

    return redirect(url_for('auth.view_cart'))


@auth.route('/decrease_quantity/<int:item_id>', methods=['POST'])
@login_required
def decrease_quantity(item_id):
    cart_item = CartItem.query.filter_by(id=item_id, cart_id=current_user.id).first()

    if cart_item:
        if cart_item.quantity > 1:
            cart_item.quantity -= 1  
        else:
            db.session.delete(cart_item)

        db.session.commit()
        flash('Removed item from your cart.', 'success')
    else:
        flash('Item not found in your cart.', 'danger')

    return redirect(url_for('auth.view_cart'))


@auth.route('/cart')
@login_required
def view_cart():
    user_cart = Cart.query.filter_by(user_id=current_user.id).first()

    total_price = 0
    total_discount = 0
    tax =  24
    shipping_fee = 5.00  
    discount_amount = 0

    if user_cart:
        items = CartItem.query.filter_by(cart_id=user_cart.id).all()
        
        # item discount from shop(if exist for a product)
        for item in items:
            discount_amount = item.product.price * (item.product.discount / 100)
            discounted_price = item.product.price - discount_amount
            total_price += discounted_price * item.quantity  
            total_discount += discount_amount * item.quantity

        # user input code discount
        user_code_discount_percentage = session.get('discount', 0)
        user_code_discount_amount = total_price * (user_code_discount_percentage / 100)
        user_price_after_discount_code = total_price - user_code_discount_amount

        tax_included = round(total_price * (tax / 100))

        if discount_amount or user_code_discount_amount:
            if total_price > 100 :
                shipping_fee_after = 0.00  
                grand_total = total_price - discount_amount - user_code_discount_amount
            else:
                shipping_fee_after = 5.00  
                grand_total = round(total_price + shipping_fee, 2) - discount_amount - user_code_discount_amount
        else:
            if total_price >= 100 :
                shipping_fee_after = 0.00  
                grand_total = total_price
            else:
                shipping_fee_after = 5.00  
                grand_total = round(total_price + shipping_fee, 2)

        return render_template('cart.html', items=items, total_price=total_price, tax=tax, shipping_fee=shipping_fee,
                               grand_total=grand_total, total_discount=total_discount,
                               user_code_discount_percentage=user_code_discount_percentage,
                               user_code_discount_amount=user_code_discount_amount,
                               user_price_after_discount_code=user_price_after_discount_code,
                               tax_included=tax_included,
                               shipping_fee_after=shipping_fee_after)
    else:
        flash('Your cart is empty.', 'info')
        return render_template('cart.html', items=[], total_price=0, total_discount=0)
    


@auth.route('/apply_discount', methods=['POST'])
@login_required
def apply_discount():
   
    user_discount_code = request.form.get('discount_code')
    user_code = User.query.filter_by(user_discount=current_user.user_discount).first()
    db.session.add(user_code)
    db.session.commit()

    if  user_discount_code  == "NEW10":
        user_code_discount_percentage = 10
        session['discount'] = user_code_discount_percentage
        flash(f"Discount code applied: {user_code_discount_percentage}% off", 'success')
    else:
        flash('Invalid discount code', 'danger')

    return redirect(url_for('auth.view_cart'))


@auth.route('/checkout')
@login_required
def checkout():
    user_code = User.query.filter_by(user_discount=current_user.user_discount).first()
    cart_items = CartItem.query.filter_by(cart_id=current_user.id).all()
    grand_total= sum(item.product.price * item.quantity for item in cart_items)
    
    if not user_code == 10 :
        discount_amount = grand_total * (10 / 100)
        grand_total = grand_total - discount_amount


    if grand_total < 100:
        grand_total = grand_total + 5.00
    
    return render_template('checkout.html',
                            grand_total=grand_total,
                            discount_amount=discount_amount,
                            user_code =user_code ,
                            stripe_public_key='pk_test_51PyIz6GCnsDUo2I6pa9gwkEqpk7KGOAiLT4frLH4ODssM1xWwGh2hiD97WUwS43qpta5GErUQpPKRjLZAb6Ovx1C00l88oWPWb')



@auth.route('/process_payment', methods=['POST', 'GET'])
@login_required
def process_payment():
    token = request.form.get('stripeToken')  
    amount = request.form.get('amount')  

    if not token or not amount :
        flash('Error processing payment. Please try again.', 'danger')

website/views.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user
from .models import Product


views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
def home():
    return render_template('index.html')


@views.route("/<string:page_name>", methods=['GET', 'POST'])
def html_page(page_name):
    products = Product.query.all()
    return  render_template(page_name , products=products)


@views.route('/confirm.html', methods=['GET', 'POST'])
def created():
    return render_template('confirm.html')


@views.route('/glasses.html', methods=['GET', 'POST'])
def view_glasses():
    products = Product.query.all()
    return  render_template('glasses.html',products=products)


@views.route("/<string:product_name>", methods=['GET', 'POST'])
def ppage(page_name):
    return  render_template(page_name.html)


@views.route('/cart.html')
@login_required
def cart():
    return render_template('cart.html', current_user=current_user)


@views.route('/order_confirmation.html')
@login_required
def order_confirmation():
    return render_template('order_confirmation.html', current_user=current_user)

website/templates/about.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>sungla</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="./static/css/bootstrap.min.css">
      <!-- style css -->
      <link rel="stylesheet" href="./static/css/style.css">
      <!-- Responsive-->
      <link rel="stylesheet" href="./static/css/responsive.css">
      <!-- fevicon -->
      <link rel="icon" href="images/fevicon.png" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="./static/css/jquery.mCustomScrollbar.min.css">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
   </head>
   <!-- body -->
   <body class="main-layout position_head">
      <!-- loader  -->
      <div class="loader_bg">
         <div class="loader"><img src="./static/images/loading.gif" alt="#" /></div>
      </div>
      <!-- end loader -->
      <!-- header -->
      <header>
         <!-- header inner -->
         <div class="header">
            <div class="container-fluid">
               <div class="row">
                  <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                     <div class="full">
                        <div class="center-desk">
                           <div class="logo">
                              <a href="index.html"><img src="./static/images/logo.png" alt="#" /></a>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                     <nav class="navigation navbar navbar-expand-md navbar-dark ">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarsExample04">
                           <ul class="navbar-nav mr-auto">
                              <li class="nav-item ">
                                 <a class="nav-link" href="index.html">Home</a>
                              </li>
                              <li class="nav-item active">
                                 <a class="nav-link" href="about.html">About</a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="glasses.html">Our Glasses</a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="contact.html">Contact Us</a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="login.html">Login</a>
                              </li>
                              <li class="nav-item d_none">
                                 <a class="nav-link" href="sign_up.html">Register</a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                              </li>
                              <li class="nav-item d_none sea_icon">
                                 <a class="nav-link" href="{{ url_for('auth.view_cart') }}"><i class="fa fa-shopping-bag" aria-hidden="true"></i></a>
                              </li>
                              <li class="nav-item d_none sea_icon"></li>
                                  <a class="nav-link" href="#"><i class="fa fa-search" aria-hidden="true"></i></a>
                              </li>
                           </ul>
                        </div>
                     </nav>
                  </div>
               </div>
            </div>
         </div>
      </header>
      <!-- end header inner -->
      <!-- end header -->
      <!-- about section -->
      <div class="about">
         <div class="container">
            <div class="row d_flex">
               <div class="col-md-5">
                  <div class="about_img">
                     <figure><img src="./static/images/about_img.png" alt="#"/></figure>
                  </div>
               </div>
               <div class="col-md-7">
                  <div class="titlepage">
                     <h2>About Our Shop</h2>
                     <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.</p>
                  </div>
                  <a class="read_more" href="#">Read More</a>
               </div>
            </div>
         </div>
      </div>
      <!-- about section -->
      <!--  footer -->
      <footer>
         <div class="footer">
            <div class="container">
               <div class="row">
                  <div class="col-md-8 offset-md-2">
                     <ul class="location_icon">
                        <li><a href="#"><i class="fa fa-map-marker" aria-hidden="true"></i></a><br> Location</li>
                        <li><a href="#"><i class="fa fa-phone" aria-hidden="true"></i></a><br> +01 1234567890</li>
                        <li><a href="#"><i class="fa fa-envelope" aria-hidden="true"></i></a><br> demo@gmail.com</li>
                     </ul>
                  </div>
               </div>
            </div>
            <div class="copyright">
               <div class="container">
                  <div class="row">
                     <div class="col-md-12">
                        <p>© 2024 Sungla. All Rights Reserved. </a></p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </footer>
      <!-- end footer -->
      <!-- Javascript files-->
      <script src="./static/js/jquery.min.js"></script>
      <script src="./static/js/popper.min.js"></script>
      <script src="./static/js/bootstrap.bundle.min.js"></script>
      <script src="./static/js/jquery-3.0.0.min.js"></script>
      <!-- sidebar -->
      <script src="./static/js/jquery.mCustomScrollbar.concat.min.js"></script>
      <script src="./static/js/custom.js"></script>
   </body>  
</html>

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>sungla</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="./static/css/bootstrap.min.css">
      <!-- style css -->
      <link rel="stylesheet" href="./static/css/style.css">
      <!-- Responsive-->
      <link rel="stylesheet" href="./static/css/responsive.css">
      <!-- fevicon -->
      <link rel="icon" href="images/fevicon.png" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="./static/css/jquery.mCustomScrollbar.min.css">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
   </head>
   <!-- body -->
   <body class="main-layout position_head">
      <!-- loader  -->
      <div class="loader_bg">
         <div class="loader"><img src="./static/images/loading.gif" alt="#" /></div>
      </div>
      <!-- end loader -->
      <!-- header -->
      <header>
         <!-- header inner -->
         <div class="header">
            <div class="container-fluid">
               <div class="row">
                  <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                     <div class="full">
                        <div class="center-desk">
                           <div class="logo">
                              <a href="index.html"><img src="./static/images/logo.png" alt="#" /></a>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                     <nav class="navigation navbar navbar-expand-md navbar-dark ">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarsExample04">
                           <ul class="navbar-nav mr-auto">
                              <li class="nav-item ">
                                 <a class="nav-link" href="index.html">Home</a>
                              </li>
                              <li class="nav-item ">
                                 <a class="nav-link" href="about.html">About</a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="glasses.html">Our Glasses</a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="contact.html">Contact Us</a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="login.html">Login</a>
                              </li>
                              <li class="nav-item d_none">
                                 <a class="nav-link" href="sign_up.html">Register</a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                              </li>
                              <li class="nav-item d_none sea_icon">
                                 <a class="nav-link" href="{{ url_for('auth.view_cart') }}"><i class="fa fa-shopping-bag" aria-hidden="true"></i></a>
                              </li>
                              <li class="nav-item d_none sea_icon"></li>
                                  <a class="nav-link" href="#"><i class="fa fa-search" aria-hidden="true"></i></a>
                              </li>
                           </ul>
                        </div>
                     </nav>
                  </div>
               </div>
            </div>
         </div>
      </header>
      
   
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        <ul class=flashes>
        {% for category, message in messages %}
            {% if category == 'success' %}
               <div class="alert alert-success alter-dismissable fade show" role="alert">
               {{ message }}
               <button type="button" class="close" data-dismiss="alert">
                  <span aria-hidden="true">&times;</span>
               </button>
               </div>
            {% else %}
               <div class="alert alert-danger alter-dismissable fade show" role="alert">
               {{ message }}
               <button type="button" class="close" data-dismiss="alert">
                  <span aria-hidden="true">&times;</span>
               </button>
            </div>
            {% endif %}
        {% endfor %}
        </ul>
      {% endif %}
      {% endwith %}


      <div class="container">{% block content %} {% endblock %}</div>
      
      <!-- about section -->
      <!--  footer -->
      <footer>
         <div class="footer">
            <div class="container">
               <div class="row">
                  <div class="col-md-8 offset-md-2">
                     <ul class="location_icon">
                        <li><a href="#"><i class="fa fa-map-marker" aria-hidden="true"></i></a><br> Location </li>
                        <li><a href="#"><i class="fa fa-phone" aria-hidden="true"></i></a><br> +01 1234567890</li>
                        <li><a href="#"><i class="fa fa-envelope" aria-hidden="true"></i></a><br> demo@gmail.com</li>
                     </ul>
                  </div>
               </div>
            </div>
            <div class="copyright">
               <div class="container">
                  <div class="row">
                     <div class="col-md-12">
                        <p>© 2024 Sungla. All Rights Reserved. </a></p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </footer>
      <!-- end footer -->
      <!-- Javascript files-->
      <script src="./static/js/jquery.min.js"></script>
      <script src="./static/js/popper.min.js"></script>
      <script src="./static/js/bootstrap.bundle.min.js"></script>
      <script src="./static/js/jquery-3.0.0.min.js"></script>
      <!-- sidebar -->
      <script src="./static/js/jquery.mCustomScrollbar.concat.min.js"></script>
      <script src="./static/js/custom.js"></script>

   </body>  
</html>

website/templates/cart.html
{% extends "base.html" %} {% block title %}Signup{% endblock %} {% block content %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Shopping Cart</title>
    <script src="https://js.stripe.com/v3/"></script>
</head>

<body>
    <h1>Your Cart</h1>

    {% if items %}
        <ul>
            {% for item in items %}

                <li>
                    {{ item.product.name }} - Quantity: {{ item.quantity }} - 
                    Original Price: {{ item.product.price }} € - 
                    Discount: {{ item.product.discount }} % - 
                    Final Price: {{ "%.2f" | format(item.product.price  * item.quantity * (1 - item.product.discount / 100))}} €
                </li>
                <form method="POST" action="{{ url_for('auth.decrease_quantity', item_id=item.id) }}">
                    <button type="submit">-</button>
                </form>
        
                <form method="POST" action="{{ url_for('auth.increase_quantity', item_id=item.id) }}">
                    <button type="submit">+</button>
                </form>
        
                <form method="POST" action="{{ url_for('auth.remove_from_cart', item_id=item.id) }}">
                    <button type="submit">Remove</button>
                </form>
            {% endfor %}
        </ul>
        <hr>
        <h3>Subtotal: {{ total_price }} € </h3>
        <p>Tax(included): {{ tax_included }} € </p>
        <p>Shipping Fee: {{ shipping_fee_after }} € </p>
        <form method="POST" action="{{ url_for('auth.apply_discount') }}">
            <input type="text" name="discount_code" placeholder="Enter Discount Code">
            <button type="submit">Apply</button>
        </form>
        <hr>
        {% if user_code_discount_amount %}
            <h3>Total Discount: {{ user_code_discount_amount }} € </h3>
        {% endif %}
        <h3>Grand Total: {{ grand_total }} € </h3>
    {% else %}
        <p>Your cart is empty.</p>
    {% endif %}

    <h3>
    <a href="{{ url_for('views.view_glasses') }}">Continue Shopping</a>
    </h3>

    <form action="{{ url_for('auth.process_payment') }}" method="POST" id="payment-form">
        <div class="form-row"></div>
            <label for="card-element"></label>
            <div id="card-element">
            
            <div id="card-errors" role="alert"></div>
            </div>
        </div>
    
        <input type="hidden" name="amount" value="{{ grand_total }}">  
        <h3>
            <button type="submit"> Pay {{ grand_total }} € </button>
        </h3>
    </form>
    
    
</body>
</html>

{% endblock %}

website/templates/checkout.html
{% extends "base.html" %} {% block title %}Signup{% endblock %} {% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Checkout</title>
    <script src="https://js.stripe.com/v3/"></script>
</head>
<body>
    <h2>Checkout</h2>
    <form id="payment-form" action="{{ url_for('auth.process_payment') }}" method="POST">
        <input type="hidden" name="amount" value="{{ grand_total }}">

        <div id="card-element"></div>
        <h3>
        <button id="submitButton">Pay {{ grand_total }} € </button>
        </h3>
        <div id="card-errors" role="alert"></div>
    </form>

    <script>
        var stripe = Stripe('pk_test_51PyIz6GCnsDUo2I6pa9gwkEqpk7KGOAiLT4frLH4ODssM1xWwGh2hiD97WUwS43qpta5GErUQpPKRjLZAb6Ovx1C00l88oWPWb');  // Replace with your actual Stripe public key
        var elements = stripe.elements();
    
       
        var card = elements.create('card');
    
        
        card.mount('#card-element');
    
        
        var form = document.getElementById('payment-form');
    
        form.addEventListener('submit', function(event) {
            event.preventDefault();  
    
           
            stripe.createToken(card).then(function(result) {
                if (result.error) {
                    var errorElement = document.getElementById('card-errors');
                    errorElement.textContent = result.error.message;
                } else {
                    stripeTokenHandler(result.token);
                }
            });
        });
    
        function stripeTokenHandler(token) {
            var hiddenInput = document.createElement('input');
            hiddenInput.setAttribute('type', 'hidden');
            hiddenInput.setAttribute('name', 'stripeToken');
            hiddenInput.setAttribute('value', token.id);
            form.appendChild(hiddenInput);
            form.submit();
        }
    </script>
</body>
</html>



{% endblock %}

website/templates/confirm.html
{% extends "base.html" %} {% block title %}Signed up{% endblock %} {% block content %}
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
{% endblock %}

website/templates/glass2.html
{% extends "base.html" %} {% block title %}Signup{% endblock %} {% block content %}




{% for product in products %}
<li>
    {% if product ==  products[1] %}
        <h2>{{ product.name }}</h2>
            <p>Price: </span>{{ product.price }}<span class="blu"> € </p>
            <p>Description: {{ product.description }}</p>
            {% if product.photo %}
                <div class="container-fluid">
                    <div class="row">
                    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
                        <div class="glasses_box">
                            <figure><img src="./static/photos/{{ product.name }}.png" alt="{{ product.name }}"/></figure>
                        </div>
                    </div>
                    <form action="{{ url_for('auth.add_to_cart', product_id=product.id) }}" method="POST">
                        <input type="submit" value="Add to Cart">
                    </form>
            {% endif %}
        {% endif %}
</li> 
{% endfor %}

{% endblock %} 